---
services:
  envoy:
    image: envoyproxy/envoy:v1.24.1
    ports:
      - ${PORT-8080}:8080
    volumes:
      - ./test/envoy.yaml:/etc/envoy/envoy.yaml
      - ./.bin/proxy-wasm-http-header-rename.wasm:/etc/envoy/proxy-wasm-http-header-rename.wasm
    command: /docker-entrypoint.sh envoy -c /etc/envoy/envoy.yaml --log-format '%L%m%d %T.%e %t envoy/%@] [%t][%n]%v' --log-format-escaped

  upstream:
    image: ghcr.io/110y/echoserver/echoserver:0.0.6
    ports:
      - 9091:5000

volumes:
  go-pkg-mod:
